% Plots EMG data for each trial (each row is a trial, and each column is a
% different EMG channel)
subplot(6,4,1)
plot(filteredEMGdata(:,2),'DisplayName','filteredEMGdata(:,end)','YDataSource','filteredEMGdata(:,end)');figure(gcf)
title('Left Hand EMG')
ylabel('Trial 1')
subplot(6,4,2)
plot(filteredEMGdata(:,3),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
title('Right Hand EMG')
subplot(6,4,3)
plot(filteredEMGdata(:,4),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
title('Left Foot EMG')
subplot(6,4,4)
plot(filteredEMGdata(:,5),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
title('Right Foot EMG')
subplot(6,4,5)
plot(filteredEMGdata2(:,2),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
ylabel('Trial 2')
subplot(6,4,6)
plot(filteredEMGdata2(:,3),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,7)
plot(filteredEMGdata2(:,4),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,8)
plot(filteredEMGdata2(:,5),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,9)
plot(filteredEMGdata3(:,2),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
ylabel('Trial 3')
subplot(6,4,10)
plot(filteredEMGdata3(:,3),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,11)
plot(filteredEMGdata3(:,4),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,12)
plot(filteredEMGdata3(:,5),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,13)
plot(filteredEMGdata4(:,2),'DisplayName','filteredEMGdata(:,end)','YDataSource','filteredEMGdata(:,end)');figure(gcf)
ylabel('Trial 4')
subplot(6,4,14)
plot(filteredEMGdata4(:,3),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,15)
plot(filteredEMGdata4(:,4),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,16)
plot(filteredEMGdata4(:,5),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,17)
plot(filteredEMGdata5(:,2),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
ylabel('Trial 5')
subplot(6,4,18)
plot(filteredEMGdata5(:,3),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,19)
plot(filteredEMGdata5(:,4),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,20)
plot(filteredEMGdata5(:,5),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,21)
plot(filteredEMGdata6(:,2),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
ylabel('Trial 6')
subplot(6,4,22)
plot(filteredEMGdata6(:,3),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,23)
plot(filteredEMGdata6(:,4),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)
subplot(6,4,24)
plot(filteredEMGdata6(:,5),'DisplayName','filteredEMGdata2(:,end)','YDataSource','filteredEMGdata2(:,end)');figure(gcf)